### ISSUE TITLE
unable to connect to server, error missing block ids

### ISSUE THREAD

**Issue by Mudlornum** [KlutzLament/MancaveLAN-Minecraft#1]
When connecting after fresh install, server states missing block ids, fatal error.

**Comment by KlutzLament** [comment]
The picture and a log would be things you could include here.

**Comment by KlutzLament** [comment]
Found the problem. Some stuff used in testing was left on the server.

**Comment by Mudlornum** [comment]
https://cdn.discordapp.com/attachments/278223203996794892/281183671766089739/unknown.png
