### ISSUE TITLE
Can't place objects against blocks with an inventory

### ISSUE THREAD

**Issue by PhantomQuasar** [KlutzLament/MancaveLAN-Minecraft#11]
As of right now in the game, just like the title says, you can't place any kind of item or block against an inventory block (IE chests, hoppers, transfer nodes).
Normally you crouch/use to place a hopper against a chest or a a transfer node against a hopper, but when you do this on the server currently it briefly places the desired block down but then it quickly vanishes and you are brought to the inventory screen as if you had just access the inventory rather than placed something against it.
This is a serious bug since a lot of functions depend on the ability to place blocks on inventory blocks for sorting and transferring and the like.

**Comment by KlutzLament** [comment]
The problem is with the mod Valkyrien Warfare. I will be removing the mod.
