### ISSUE TITLE
Calculator can not be powered, client crash

### ISSUE THREAD

**Issue by Mudlornum** [KlutzLament/MancaveLAN-Minecraft#3]
Calculator mod item Calculator when placed into a power cube will create the client.  Using a docking station no power flows through it, placing items into calculator mounted to docking station also crashes client.  Unable to craft any other items in the mod as they require to use the calculator item at least once.

**Comment by Mudlornum** [comment]
[crash-2017-02-25_16.34.32-client.txt](https://github.com/KlutzLament/MancaveLAN-Minecraft/files/801565/crash-2017-02-25_16.34.32-client.txt)

**Comment by KlutzLament** [comment]
This should be fixed with the most recent pack update (0.7.1a). Please test.

**Comment by Mudlornum** [comment]
Testing complete, appears resolved.
