### ISSUE TITLE
Chickens Mod - some chicken types not spawning

### ISSUE THREAD

**Issue by Mudlornum** [KlutzLament/MancaveLAN-Minecraft#4]
No Sand or Log chickens in world.  Found a few Flint chickens and Nether Chickens, but the other two core types, again Sand and Log are missing.  Much traveling has produced no results.  Others on server have failed to find these 2.  No crafting recipe for these, stopping advancement in this mod.

**Comment by KlutzLament** [comment]
The config file says they should be spawning.

**Comment by Mudlornum** [comment]
Is there a way to see if sand and log chickens exist in any chunks?  I've seen none, and no other player has :(

**Comment by Mudlornum** [comment]
Reviewing I found 1 log chicken in a RFTOOLS - DIMENSIONS world.  Still no Sand found, but it appears they 'can' spawn, just are very very rare.
