### ISSUE TITLE
Botania Elven Gateway not doing trades

### ISSUE THREAD

**Issue by Mudlornum** [KlutzLament/MancaveLAN-Minecraft#5]
Block Elven Gateway Core, when powered with mana should allow trades.  The book trade worked, but livingwood for dreamwood trade is eatting the livingwood, and 2 manasteel ingots is not producing the Elementium ingot

**Comment by KlutzLament** [comment]
Botania was updated. Are you still having issues?

**Comment by Mudlornum** [comment]
Issue resolved.  Trades are working.
