### ISSUE TITLE
Sm00kie Logon Issue

### ISSUE THREAD

**Issue by Sm00kie** [KlutzLament/MancaveLAN-Minecraft#6]
I get the error that there are fatally missing blocks and items when I try to connect to the server.  I have  the logs just from opening Technic, Choosing ManCave Mod Pack and Running it and Ending with the error (last line is below) however it is too many characters for a full log post but I do have it as a TXT File.  Will also post a screenshot to facebook group.

Technic Logs-----------

[B#349] 2017/03/15 21:01:17 [INFO]  [21:01:17] [Netty Client IO #1/ERROR] [FML]: Failed to connect to server: there are 2 missing blocks and items

**Comment by KlutzLament** [comment]
Can you post your forge log? (fml-client-latest.log in the logs folder) Please use a service like pastebin.com or gist.github.com and paste the link here.

**Comment by KlutzLament** [comment]
Fixed with version 0.9.2 of the pack.
