### ISSUE TITLE
No method to obtain dragon eggs past original vanilla dragon egg

### ISSUE THREAD

**Issue by Mudlornum** [KlutzLament/MancaveLAN-Minecraft#8]
The Mod extra utilities requests a number of dragon eggs for it's end game content.  The RFTOOLS DIMENSIONS mod allows for a 'world' of dragons which when killed should spawn an exit portal with an egg on it.  (noted on a youtube series, unable to replicate in modpack we have).  This did not work.  

There is no recipe for said egg, and the other method of using UU-Matter to create it may need to be enabled (has not been tested as yet due to extreme level of time investment to work through IC2 to confirm).

All in all, would like a way to get more dragon egg items to progress into end game content of Extra Utilities.

**Comment by KlutzLament** [comment]
Have you tried respawning the dragon in The End?

**Comment by KlutzLament** [comment]
I will look into adding dragon egg chickens until a better solution can be found.

**Comment by Mudlornum** [comment]
Respawning dragon does not drop additional eggs.  This was tested.

**Comment by KlutzLament** [comment]
What end game content requires dragon eggs? All I can see is the dragon egg generator.

**Comment by KlutzLament** [comment]
Err.. dragon egg mill

**Comment by Mudlornum** [comment]
The end game sword Kikoku requires some ender dragon eggs in the recipe.
